// src/blocks/index.ts
import './mostrarBlock';
import './guardarBlock';
import './numeroBlock';
import './textoBlock';
import './siBlock';
import './repetirBlock';
import './preguntarBlock';
import './operacionesBlock';